import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { gql, useQuery } from "@apollo/client";
import { getAllContacts } from "../graphql/queries";


export default function Home() {

  const router = useRouter();
  const { data, loading, error } = useQuery(gql(getAllContacts));
  const [contacts, setContacts] = React.useState<[] | undefined>([]);

  React.useEffect(() => {
    if (data && !loading && !error) {
      setContacts(data.getAllContacts.contacts);
    } else if (error) {
      console.error("Error fetching contacts", error);
    }
  }, [data, loading, error]);

  return (
    <>
      <Head>
        <title>Frontend-test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home">
        <div className="list-container">
          <div className="list-header">
            <h1>Contacts</h1>
            <div className="list-header-search">
              <input type="text" placeholder="Search" />
            </div>
          </div>
          <div className="list-my-card">
            <span className="my-card-user-icon" />
            <div className="my-card-info">
              <h2>Cristian</h2>
              <p>My Card</p>
            </div>
          </div>
          <div className="list-contacts">
            {contacts ? (
              contacts.map((contact: any) => (
                <div
                  className="contact"
                  key={contact.id}
                  onClick={() => router.push(`/contactdetails/${contact.id}`)}
                >
                  <p>{contact.name}</p>
                </div>
              ))
            ) : (
              <h2>No Contacts</h2>
            )}
          </div>
        </div>
      </main>
    </>
  );
}