import React from "react";
import Head from "next/head";

export const getStaticProps = async () => {

  const res = await fetch(`http://localhost:3000/api/hello`);
  const data = await res.json();

  return {
    props: { contacts: data}
  }

}

export default function Home({ contacts }) {
  // Your code here

  return (
    <>
      <Head>
        <title>Frontend-test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home">
        {/* Your code here */}
        <div>
          {contacts.map(contact => (
            <div key={contact.id}>
              <a>
                <h3  className="contactList">{ contact.name }</h3>
              </a>
            </div>
          ))}
        </div>
        {/* ∆∆∆∆∆∆∆∆∆∆∆∆∆∆ */}
      </main>
    </>
  );
}
